// Date: 8/4/2014 12:50:50 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.ancientrelics.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCrystalEnergizer extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Actuator1;
    ModelRenderer Actuator2;
    ModelRenderer Eye;
  
  public ModelCrystalEnergizer()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Eye.Crown", 0, 23);
    setTextureOffset("Eye.ThumbBase1", 0, 18);
    setTextureOffset("Eye.ThumbBase2", 4, 18);
    setTextureOffset("Eye.Wrist1", 0, 16);
    
      Base1 = new ModelRenderer(this, 24, 18);
      Base1.addBox(-5F, 0F, -5F, 10, 4, 10);
      Base1.setRotationPoint(0F, 20F, 0F);
      Base1.setTextureSize(64, 32);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 32, 5);
      Base2.addBox(-4F, 0F, -4F, 8, 4, 8);
      Base2.setRotationPoint(0F, 16F, 0F);
      Base2.setTextureSize(64, 32);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Base3 = new ModelRenderer(this, 0, 0);
      Base3.addBox(-3F, 0F, -3F, 6, 4, 6);
      Base3.setRotationPoint(0F, 12F, 0F);
      Base3.setTextureSize(64, 32);
      Base3.mirror = true;
      setRotation(Base3, 0F, 0F, 0F);
      Actuator1 = new ModelRenderer(this, 0, 27);
      Actuator1.addBox(-1F, 0F, -1F, 2, 3, 2);
      Actuator1.setRotationPoint(0F, 9F, 0F);
      Actuator1.setTextureSize(64, 32);
      Actuator1.mirror = true;
      setRotation(Actuator1, 0F, 0F, 0F);
      Actuator2 = new ModelRenderer(this, 0, 27);
      Actuator2.addBox(-1F, 0F, -1F, 2, 3, 2);
      Actuator2.setRotationPoint(0F, 9F, 0F);
      Actuator2.setTextureSize(64, 32);
      Actuator2.mirror = true;
      setRotation(Actuator2, 0F, 0.7853982F, 0F);
    Eye = new ModelRenderer(this, "Eye");
    Eye.setRotationPoint(0F, 8.5F, 0F);
    //setRotation(Eye, 0.6981317F, 0F, 0F);
    Eye.mirror = true;
      Eye.addBox("Crown", -3.5F, -7.5F, -0.5F, 7, 3, 1);
      Eye.addBox("ThumbBase1", -2.5F, -4.5F, -0.5F, 1, 4, 1);
      Eye.addBox("ThumbBase2", 1.5F, -4.5F, -0.5F, 1, 4, 1);
      Eye.addBox("Wrist1", -4.5F, -0.5F, -0.5F, 9, 1, 1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base1.render(f5);
    Base2.render(f5);
    Base3.render(f5);
    Actuator1.render(f5);
    Actuator2.render(f5);
    Eye.render(f5);
  }
  
  public void renderModel(float f ) {
	  Base1.render(f);
	  Base2.render(f);
	  Base3.render(f);
	  Actuator1.render(f);
	  Actuator2.render(f);
	  Eye.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
